#version 450

// Image copy using image2D
layout(local_size_x = 1, local_size_y = 1) in;

// Input image (RGBA32F)
layout(binding = 0, rgba32f) uniform readonly image2D imgIn;
// Output image (RGBA32F)
layout(binding = 1, rgba32f) uniform writeonly image2D imgOut;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec4 pixel = imageLoad(imgIn, coord);
    imageStore(imgOut, coord, pixel);
}